apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/a4b4d0ec-57a9-46f4-86eb-dd6b85595c86/resourcegroups/alura-curso-kubernetes/providers/Microsoft.Compute/disks/pv-disk
    volumeAttributes:
      fsType: ext4